-- ============================================================
-- LEGACY FILE — DO NOT USE
--
-- All tables and seed data originally defined here have been
-- merged into database/bari_lms_postgresql.sql, which is the
-- canonical schema for bariLMS.
--
-- This file is kept for historical reference only and must NOT
-- be applied to any database.
-- ============================================================
